name: active-divergence
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - "numpy<2"
  - scipy
  - matplotlib
  - librosa
  - tqdm
  - jupyter
  - ipywidgets
  - tensorboard
  - pandas
  - pip
  - pip:
    - soundfile
    - torchcrepe
    - torchsynth==1.0.2
    - pytorch-lightning<2.0
    - setuptools<70
